name: gastromind
description: "A new Flutter project."

version: 3.0.1+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  provider: ^6.1.2
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  uuid: ^4.5.1
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  reorderable_grid_view: ^2.2.8
  url_launcher: ^6.3.2
  network_info_plus: ^5.0.0
  google_fonts: ^6.0.0
  animated_text_kit: ^4.2.2
  image_picker: ^0.8.7+4
  image: ^4.0.17
  flutter_secure_storage: ^10.0.0
  shimmer: ^3.0.0
  open_file: ^3.3.2 # Dosyaları açmak için
  pdf: ^3.10.8
  printing: ^5.12.0
  pdfx: ^2.5.0
  showcaseview: ^5.0.1
  syncfusion_flutter_pdfviewer: ^31.2.3
  material_design_icons_flutter: ^7.0.7296
  qr_flutter: ^4.1.0
  flutter_html: ^3.0.0
  share_plus: ^12.0.1
  flutter_dotenv: ^6.0.0
  flutter_gemini: ^3.0.0
  pub_semver: ^2.2.0
  package_info_plus: ^9.0.0
  sqflite_common_ffi: ^2.3.3
  marquee: ^2.3.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  mobile_scanner: ^7.1.4
  in_app_purchase: ^3.2.3
  device_info_plus: ^12.3.0
  file_picker: ^10.3.10
  lottie: ^3.3.2
  webview_flutter: ^4.13.1
  firebase_storage: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/gastrofy.png"
  min_sdk_android: 21
  macos:
    generate: true
    image_path: "assets/gastrofy.png"
  windows:
    generate: true
    image_path: "assets/gastrofy.png"
    icon_size: 256 # Windows ikon kalitesi için önerilir

flutter:
  uses-material-design: true
  assets:
    - assets/gastrofy.png
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-Italic.ttf
    - assets/fonts/Roboto-BoldItalic.ttf
    - .env
    - assets/animations/gastromindwelcomeanimation.json
    - assets/animations/gastromindwelcomenote.json
    - assets/animations/gastromindwelcomeorder.json
    - assets/animations/gastromindwelcomereport.json
    - assets/animations/gastromindwelcometableintelligence.json
    - assets/animations/gastromindwelcomeoncredit.json
    - assets/animations/gastromindwelcomepersonel.json
    - assets/animations/gastromindwelcomesecurity.json
    - assets/animations/gastromindwelcometranslate.json
   #- assets/embeddinggemma-300M_seq1024_mixed-precision.tflite
   #- assets/sentencepiece.model
   
# Bu bölüm doğru ve değiştirilmedi
