// File generated by Antigravity - Restored original GastroMind project config.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAo_vGgsodwFWyunvUsVfhAibqhNMeP1A',
    appId: '1:329038116855:web:6955f016b9457c5e5060f2',
    messagingSenderId: '329038116855',
    projectId: 'gastromind-144a9',
    authDomain: 'gastromind-144a9.firebaseapp.com',
    storageBucket: 'gastromind-144a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAo_vGgsodwFWyunvUsVfhAibqhNMeP1A',
    appId: '1:329038116855:android:c4b8d7a1e0b9c2f6d5e4a3',
    messagingSenderId: '329038116855',
    projectId: 'gastromind-144a9',
    storageBucket: 'gastromind-144a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAo_vGgsodwFWyunvUsVfhAibqhNMeP1A',
    appId: '1:329038116855:ios:f1e2d3c4b5a69788d7c6b5',
    messagingSenderId: '329038116855',
    projectId: 'gastromind-144a9',
    storageBucket: 'gastromind-144a9.firebasestorage.app',
    iosBundleId: 'com.gastromind.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAo_vGgsodwFWyunvUsVfhAibqhNMeP1A',
    appId: '1:329038116855:ios:f1e2d3c4b5a69788d7c6b5',
    messagingSenderId: '329038116855',
    projectId: 'gastromind-144a9',
    storageBucket: 'gastromind-144a9.firebasestorage.app',
    iosBundleId: 'com.gastromind.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAo_vGgsodwFWyunvUsVfhAibqhNMeP1A',
    appId: '1:329038116855:web:6955f016b9457c5e5060f2',
    messagingSenderId: '329038116855',
    projectId: 'gastromind-144a9',
    authDomain: 'gastromind-144a9.firebaseapp.com',
    storageBucket: 'gastromind-144a9.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCAo_vGgsodwFWyunvUsVfhAibqhNMeP1A',
    appId: '1:329038116855:web:6955f016b9457c5e5060f2',
    messagingSenderId: '329038116855',
    projectId: 'gastromind-144a9',
    authDomain: 'gastromind-144a9.firebaseapp.com',
    storageBucket: 'gastromind-144a9.firebasestorage.app',
  );
}
